CREATE TABLE ASESOR (
       CODIGO_EMPLEADO CHAR(15) NOT NULL
     , NOMBRE CHAR(15) NOT NULL
     , PRIMARY KEY (CODIGO_EMPLEADO)
);

CREATE TABLE CLIENTE (
       NIF_CLIENTE CHAR(15) NOT NULL
     , NOMBRE CHAR(15) NOT NULL
     , APELLIDOS CHAR(30)
     , PRIMARY KEY (NIF_CLIENTE)
);

CREATE TABLE INMUEBLE (
       COD_ID CHAR(15) NOT NULL
     , CALLE CHAR(20)
     , LOCALIDAD CHAR(20)
     , FECHA_ALTA CHAR(15)
     , SUPERFICIE_TOTAL CHAR(10)
     , VENTA_ALQUILER CHAR(5)
     , CODIGO_EMPLEADO CHAR(15)
     , NIF_CLIENTE CHAR(10) NOT NULL
     , PRIMARY KEY (COD_ID)
     , CONSTRAINT FK_INMUEBLE_2 FOREIGN KEY (CODIGO_EMPLEADO)
                  REFERENCES ASESOR (CODIGO_EMPLEADO)
     , CONSTRAINT FK_INMUEBLE_1 FOREIGN KEY (NIF_CLIENTE)
                  REFERENCES CLIENTE (NIF_CLIENTE)
);

CREATE TABLE VISITA (
       FECHA CHAR(25)
     , COD_ID CHAR(15)
     , NIF_CLIENTE CHAR(15) NOT NULL
     , CODIGO_EMPLEADO CHAR(15) NOT NULL
     , COD_VISITA CHAR(15) NOT NULL
     , PRIMARY KEY (COD_VISITA)
     , CONSTRAINT FK_VISITA_1 FOREIGN KEY (COD_ID)
                  REFERENCES INMUEBLE (COD_ID)
     , CONSTRAINT FK_VISITA_2 FOREIGN KEY (NIF_CLIENTE)
                  REFERENCES CLIENTE (NIF_CLIENTE)
     , CONSTRAINT FK_VISITA_3 FOREIGN KEY (CODIGO_EMPLEADO)
                  REFERENCES ASESOR (CODIGO_EMPLEADO)
);

CREATE TABLE OFERTA (
       PRECIO CHAR(20)
     , FECHA CHAR(10)
     , COD_OFERTA CHAR(20) NOT NULL
     , COD_VISITA CHAR(15) NOT NULL
     , PRIMARY KEY (COD_OFERTA)
     , CONSTRAINT FK_OFERTA_1 FOREIGN KEY (COD_VISITA)
                  REFERENCES VISITA (COD_VISITA)
);

CREATE TABLE NAVEINDUSTRIAL (
       COD_ID CHAR(15) NOT NULL
     , NUM_PUERTAS CHAR(10)
     , CALIFICACION CHAR(10)
     , PRIMARY KEY (COD_ID)
     , CONSTRAINT FK_NAVEINDUSTRIAL_1 FOREIGN KEY (COD_ID)
                  REFERENCES INMUEBLE (COD_ID)
);

CREATE TABLE TRANSACCION (
       PRECIO_FINAL CHAR(20)
     , FECHA CHAR(15)
     , COMPRA_O_ALQUILER CHAR(5)
     , COD_TRANSACCION CHAR(20) NOT NULL
     , COD_OFERTA CHAR(10) NOT NULL
     , PRIMARY KEY (COD_TRANSACCION)
     , CONSTRAINT FK_TRANSACCION_1 FOREIGN KEY (COD_OFERTA)
                  REFERENCES OFERTA (COD_OFERTA)
);

CREATE TABLE PISO (
       COD_ID CHAR(15) NOT NULL
     , NUM_HABITACIONES CHAR(10)
     , PRIMARY KEY (COD_ID)
     , CONSTRAINT FK_PISO_1 FOREIGN KEY (COD_ID)
                  REFERENCES INMUEBLE (COD_ID)
);

